baseURL = 'https://ualiruhi.github.io'
languageCode = 'en-us'
title = "My First Website"
theme = "hugo-coder"

[author]
  name = "Ali Ruhi Unal"
  email = "ualiruhi@gmail.com"

[markup.goldmark.renderer]
  unsafe = true

[params]
  author = "Ali Ruhi Unal"
  info = "Trying to be a developer"
  description = "Create a website with Hugo!"
  keywords = "blog"
  colorScheme = "dark"

[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/ualiruhi"
[[params.social]]
  name = "RSS"
  icon = "fa fa-2x fa-rss"
  weight = 6
  url = "index.xml"
  rel = "alternate"
  type = "application/rss+xml"
[[params.social]]
name = "instagram"
icon = ""fa-brands fa-instagram"
weight = 1
url = "https://instagram.com/aliruhiunl"
[[menu.main]]
  name = "Blog"
  weight = 1
  url = "posts/"
 
