baseURL = 'https://ualiruhi.github.io'
languageCode = 'en-us'
title = "Ilk blog sayfam"
theme = "hugo-coder"

[author]
  name = "Ali Ruhi Unal"
  email = "ualiruhi@gmail.com"

[markup.goldmark.renderer]
  unsafe = true

[params]
  author = "Ali Ruhi Unal"
  info = "Ben bir geliştiriciyim"
  description = "Hugo ile websitesi kurmak"
  keywords = "blog"
  colorScheme = "dark"

[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/ualiruhi"
[[params.social]]
  name = "RSS"
  icon = "fa fa-2x fa-rss"
  weight = 6
  url = "index.xml"
  rel = "alternate"
  type = "application/rss+xml"

[[menu.main]]
  name = "Blog"
  weight = 1
  url = "posts/"
